theme: jekyll-theme-minimal
title: Split Apart
description: Mini-game prototype for a mechanic demo for GMU CS 325 Fall 2025
show_downloads: true
logo: /assets/screenshots/logo.png
github:
  zip_url: https://www.mediafire.com/file/s5c05wl2ztit58n/split_apart.zip/file
